export interface CountryData {
	name: string;
	flag: string;
}

export const fetchCountriesInEurope = (): CountryData[] => {
	const europeanCountries: CountryData[] = [
		{ name: 'Åland Islands', flag: '🇦🇽' },
		{ name: 'Albania', flag: '🇦🇱' },
		{ name: 'Andorra', flag: '🇦🇩' },
		{ name: 'Austria', flag: '🇦🇹' },
		{ name: 'Belarus', flag: '🇧🇾' },
		{ name: 'Belgium', flag: '🇧🇪' },
		{ name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
		{ name: 'Bulgaria', flag: '🇧🇬' },
		{ name: 'Croatia', flag: '🇭🇷' },
		{ name: 'Cyprus', flag: '🇨🇾' },
		{ name: 'Czechia', flag: '🇨🇿' },
		{ name: 'Denmark', flag: '🇩🇰' },
		{ name: 'Estonia', flag: '🇪🇪' },
		{ name: 'Faroe Islands', flag: '🇫🇴' },
		{ name: 'Finland', flag: '🇫🇮' },
		{ name: 'France', flag: '🇫🇷' },
		{ name: 'Germany', flag: '🇩🇪' },
		{ name: 'Gibraltar', flag: '🇬🇮' },
		{ name: 'Greece', flag: '🇬🇷' },
		{ name: 'Guernsey', flag: '🇬🇬' },
		{ name: 'Hungary', flag: '🇭🇺' },
		{ name: 'Iceland', flag: '🇮🇸' },
		{ name: 'Ireland', flag: '🇮🇪' },
		{ name: 'Isle of Man', flag: '🇮🇲' },
		{ name: 'Italy', flag: '🇮🇹' },
		{ name: 'Jersey', flag: '🇯🇪' },
		{ name: 'Kosovo', flag: '🇽🇰' },
		{ name: 'Latvia', flag: '🇱🇻' },
		{ name: 'Liechtenstein', flag: '🇱🇮' },
		{ name: 'Lithuania', flag: '🇱🇹' },
		{ name: 'Luxembourg', flag: '🇱🇺' },
		{ name: 'Malta', flag: '🇲🇹' },
		{ name: 'Moldova', flag: '🇲🇩' },
		{ name: 'Monaco', flag: '🇲🇨' },
		{ name: 'Montenegro', flag: '🇲🇪' },
		{ name: 'Netherlands', flag: '🇳🇱' },
		{ name: 'North Macedonia', flag: '🇲🇰' },
		{ name: 'Norway', flag: '🇳🇴' },
		{ name: 'Poland', flag: '🇵🇱' },
		{ name: 'Portugal', flag: '🇵🇹' },
		{ name: 'Romania', flag: '🇷🇴' },
		{ name: 'Russia', flag: '🇷🇺' },
		{ name: 'San Marino', flag: '🇸🇲' },
		{ name: 'Serbia', flag: '🇷🇸' },
		{ name: 'Slovakia', flag: '🇸🇰' },
		{ name: 'Slovenia', flag: '🇸🇮' },
		{ name: 'Spain', flag: '🇪🇸' },
		{ name: 'Svalbard and Jan Mayen', flag: '🇸🇯' },
		{ name: 'Sweden', flag: '🇸🇪' },
		{ name: 'Switzerland', flag: '🇨🇭' },
		{ name: 'Ukraine', flag: '🇺🇦' },
		{ name: 'United Kingdom', flag: '🇬🇧' },
		{ name: 'Vatican City', flag: '🇻🇦' },
	];

	return europeanCountries;
};
